const data = {
  products: [
    {
      name: 'Produto 01',
      slug: 'produto-01',
      category: 'categoria01',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Marca01',
      rating: 4.5,
      numReviews: 10,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Produto 02',
      slug: 'produto-02',
      category: 'categoria02',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 8,
      brand: 'Marca01',
      rating: 5.5,
      numReviews: 2,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Produto 03',
      slug: 'produto-03',
      category: 'categoria03',
      image: '/images/p3.jpg',
      price: 130,
      countInStock: 5,
      brand: 'Marca01',
      rating: 4.0,
      numReviews: 12,
      description: 'produto de alta qualidade',
    },
    {
      name: 'Produto 04',
      slug: 'produto-04',
      category: 'categoria04',
      image: '/images/p4.jpg',
      price: 220,
      countInStock: 10,
      brand: 'Marca01',
      rating: 6.5,
      numReviews: 3,
      description: 'produto de alta qualidade',
    },
  ],
};

export default data;
